FROM python:3.9-slim

WORKDIR /app

COPY data_preprocessing.py data/users/*.csv data/paginas/*.csv requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "data_preprocessing.py"]
